const PATHS = {
	home: '/',
	login: '/login',
	signUp: '/signUp',
	forgotPassword: '/forgotPassword',
	techInDailyLife: '/techInDailyLife',
	techInClassAndWork: '/techInClassAndWork',
	techSafetyAndPrivacy: '/techSafetyAndPrivacy',
	financeAndManagement: '/financeAndManagement',
	quiz: '/quiz',
	help: '/help',
	questionDisplay: '/questions/:questionId',
	jobSupport: '/jobSupport',
	resumeBuilder: '/resumeBuilder',
	userInformation: '/userInformation',
	generateResume: '/generateResume',
	addVideos: '/addVideos',
	restoreVideos: '/restoreVideos',
	updateVideo: '/updateVideo/:videoId/:editType',
	helpManager: '/helpManager',
	faq: '/faq',
	infoPage: '/infoPage/:title',
	addQuizQuestions: '/addQuizQuestions',
};

export default PATHS;
