const PATHS = {
	home: '/',
	login: '/login',
	signUp: '/signUp',
	forgotPassword: '/forgotPassword',
	techInDailyLife: '/techInDailyLife',
	techInClassAndWork: '/techInClassAndWork',
	techSafetyAndPrivacy: '/techSafetyAndPrivacy',
	financeAndManagement: '/financeAndManagement',
	quiz: '/quiz',
	help: '/help',
	questionDisplay: '/questions/:questionId',
	jobSupport: '/jobSupport',
	resumeBuilder: '/resumeBuilder',
	userInformation: '/userInformation',
	generateResume: '/generateResume',
	addVideos: '/addVideos',
	restoreVideos: '/restoreVideos',
	updateVideo: '/updateVideo/:videoId/:editType',
	helpManager: '/helpManager',
	addQuizQuestions: '/addQuizQuestions',
	faq: '/faq',
	newComputer: '/newComputer',
	computerType: '/computerType',
	phoneIcons: '/phoneIcons',
	emailOnPhone: '/emailOnPhone',
	mailAppDifference: '/mailAppDifference',
	schoolEmailPersonal: '/schoolEmailPersonal',
	computerErrors: '/computerErrors',
	rightClick: '/rightClick',
	dragAndDrop: '/dragAndDrop',
	trackpad: '/trackpad',
	browserSearchEngine: '/browserSearchEngine',
	browserVsApp: '/browserVsApp',
	canvas: '/canvas',
	searchWeb: '/searchWeb',
	customizeSettingsApp: '/customizeSettingsApp',
	savedFile: '/savedFile',
	cacheAndCookies: '/cacheAndCookies',
	goBackPage: '/goBackPage',
	studentEmail: '/studentEmail',
	rightEmailAccount: '/rightEmailAccount',
	professorContact: '/professorContact',
};

export default PATHS;
